/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-25 18:53:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import timeSheet.UtilWeb;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/timeSheet.tld", Long.valueOf(1621248506000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftimeSheet_005fheader_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftimeSheet_005ferror_0026_005ferror_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftimeSheet_005fheader_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftimeSheet_005ferror_0026_005ferror_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody.release();
    _005fjspx_005ftagPool_005ftimeSheet_005fheader_005fnobody.release();
    _005fjspx_005ftagPool_005ftimeSheet_005ferror_0026_005ferror_005fnobody.release();
    _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      timeSheet.form.Credentials creds = null;
      creds = (timeSheet.form.Credentials) _jspx_page_context.getAttribute("creds", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (creds == null){
        creds = new timeSheet.form.Credentials();
        _jspx_page_context.setAttribute("creds", creds, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write("\n");
        out.write("    ");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("creds"), request);
        out.write('\n');
      }
      out.write('\n');

    // If process is true, attempt to validate and process the form
    String error = null;
    if ("true".equals(request.getParameter("process"))) {
        error = creds.process(session);
        if (error == null) {

      out.write('\n');
      if (true) {
        _jspx_page_context.forward("dashboard.jsp");
        return;
      }
      out.write('\n');

        }
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        ");
 UtilWeb.checkInstall(out); 
      out.write("\n");
      out.write("        ");
 if (UtilWeb.checkSession(out, request, false)) return; 
      out.write("\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<title>PaySystem</title>\n");
      out.write("        ");
      if (_jspx_meth_timeSheet_005fheadDefault_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t");
      if (_jspx_meth_timeSheet_005fheader_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        ");
      //  timeSheet:error
      timeSheet.tags.ErrorTag _jspx_th_timeSheet_005ferror_005f0 = (timeSheet.tags.ErrorTag) _005fjspx_005ftagPool_005ftimeSheet_005ferror_0026_005ferror_005fnobody.get(timeSheet.tags.ErrorTag.class);
      boolean _jspx_th_timeSheet_005ferror_005f0_reused = false;
      try {
        _jspx_th_timeSheet_005ferror_005f0.setPageContext(_jspx_page_context);
        _jspx_th_timeSheet_005ferror_005f0.setParent(null);
        // /index.jsp(32,8) name = error type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_timeSheet_005ferror_005f0.setError(error);
        int _jspx_eval_timeSheet_005ferror_005f0 = _jspx_th_timeSheet_005ferror_005f0.doStartTag();
        if (_jspx_th_timeSheet_005ferror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ftimeSheet_005ferror_0026_005ferror_005fnobody.reuse(_jspx_th_timeSheet_005ferror_005f0);
        _jspx_th_timeSheet_005ferror_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_timeSheet_005ferror_005f0, _jsp_getInstanceManager(), _jspx_th_timeSheet_005ferror_005f0_reused);
      }
      out.write("\n");
      out.write("\t\t<div class=\"login\">\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getRequestURI());
      out.write("\" method=\"post\">\n");
      out.write("\t\t\t\t<label for=\"userName\">User Name:</label>\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"input\" name=\"userName\" id=\"userName\" >\n");
      out.write("\t\t\t\t<br /><br />\n");
      out.write("\t\t\t\t<label for=\"password\">Password:</label>\n");
      out.write("\t\t\t\t<input type=\"password\" class=\"input\" name=\"password\" id=\"password\" >\n");
      out.write("\t\t\t\t<br /><br />\n");
      out.write("\t\t\t\t<input class=\"submit\" type=\"submit\" value=\"Login\">\n");
      out.write("                <input type=\"HIDDEN\" name=\"process\" value=\"true\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("        ");
      if (_jspx_meth_timeSheet_005ffooter_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_timeSheet_005fheadDefault_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  timeSheet:headDefault
    timeSheet.tags.CommonHeadTag _jspx_th_timeSheet_005fheadDefault_005f0 = (timeSheet.tags.CommonHeadTag) _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody.get(timeSheet.tags.CommonHeadTag.class);
    boolean _jspx_th_timeSheet_005fheadDefault_005f0_reused = false;
    try {
      _jspx_th_timeSheet_005fheadDefault_005f0.setPageContext(_jspx_page_context);
      _jspx_th_timeSheet_005fheadDefault_005f0.setParent(null);
      // /index.jsp(28,8) name = displayCalendar type = java.lang.Boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_timeSheet_005fheadDefault_005f0.setDisplayCalendar(false);
      int _jspx_eval_timeSheet_005fheadDefault_005f0 = _jspx_th_timeSheet_005fheadDefault_005f0.doStartTag();
      if (_jspx_th_timeSheet_005fheadDefault_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody.reuse(_jspx_th_timeSheet_005fheadDefault_005f0);
      _jspx_th_timeSheet_005fheadDefault_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_timeSheet_005fheadDefault_005f0, _jsp_getInstanceManager(), _jspx_th_timeSheet_005fheadDefault_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_timeSheet_005fheader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  timeSheet:header
    timeSheet.tags.HeaderTag _jspx_th_timeSheet_005fheader_005f0 = (timeSheet.tags.HeaderTag) _005fjspx_005ftagPool_005ftimeSheet_005fheader_005fnobody.get(timeSheet.tags.HeaderTag.class);
    boolean _jspx_th_timeSheet_005fheader_005f0_reused = false;
    try {
      _jspx_th_timeSheet_005fheader_005f0.setPageContext(_jspx_page_context);
      _jspx_th_timeSheet_005fheader_005f0.setParent(null);
      int _jspx_eval_timeSheet_005fheader_005f0 = _jspx_th_timeSheet_005fheader_005f0.doStartTag();
      if (_jspx_th_timeSheet_005fheader_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftimeSheet_005fheader_005fnobody.reuse(_jspx_th_timeSheet_005fheader_005f0);
      _jspx_th_timeSheet_005fheader_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_timeSheet_005fheader_005f0, _jsp_getInstanceManager(), _jspx_th_timeSheet_005fheader_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_timeSheet_005ffooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  timeSheet:footer
    timeSheet.tags.FooterTag _jspx_th_timeSheet_005ffooter_005f0 = (timeSheet.tags.FooterTag) _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody.get(timeSheet.tags.FooterTag.class);
    boolean _jspx_th_timeSheet_005ffooter_005f0_reused = false;
    try {
      _jspx_th_timeSheet_005ffooter_005f0.setPageContext(_jspx_page_context);
      _jspx_th_timeSheet_005ffooter_005f0.setParent(null);
      int _jspx_eval_timeSheet_005ffooter_005f0 = _jspx_th_timeSheet_005ffooter_005f0.doStartTag();
      if (_jspx_th_timeSheet_005ffooter_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody.reuse(_jspx_th_timeSheet_005ffooter_005f0);
      _jspx_th_timeSheet_005ffooter_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_timeSheet_005ffooter_005f0, _jsp_getInstanceManager(), _jspx_th_timeSheet_005ffooter_005f0_reused);
    }
    return false;
  }
}
