/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-06-25 19:35:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import timeSheet.UtilWeb;
import timeSheet.database.entity.HourType;
import timeSheet.database.manager.HourTypeManager;
import java.util.List;

public final class manageHourTypes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/timeSheet.tld", Long.valueOf(1621248506000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftimeSheet_005fmenu_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftimeSheet_005fheader_0026_005fsub_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftimeSheet_005fmenu_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftimeSheet_005fheader_0026_005fsub_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody.release();
    _005fjspx_005ftagPool_005ftimeSheet_005fmenu_005fnobody.release();
    _005fjspx_005ftagPool_005ftimeSheet_005fheader_0026_005fsub_005fnobody.release();
    _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    ");
 if (UtilWeb.checkSession(out, request, true)) return; 
      out.write("\n");
      out.write("    ");
 HourTypeManager groupManager = new HourTypeManager(); 
      out.write("\n");
      out.write("    <title>PaySystem - Manage Hour Types</title>\n");
      out.write("    ");
      if (_jspx_meth_timeSheet_005fheadDefault_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      if (_jspx_meth_timeSheet_005fmenu_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_timeSheet_005fheader_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("    <table class=\"install\">\n");
      out.write("        ");

            List<HourType> hourTypeList = groupManager.getList();
            for (HourType hourType : hourTypeList) {
        
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td class=\"value\">");
      out.print(hourType.getName());
      out.write("</td>\n");
      out.write("            <td class=\"action\"><a href=\"editHourType.jsp?");
      out.print( HourType.Field.id);
      out.write('=');
      out.print(hourType.getId());
      out.write("\">Edit</a></td>\n");
      out.write("            <td class=\"action\"><a href=\"library/deleteHourType.jsp?");
      out.print(HourType.Field.id);
      out.write('=');
      out.print(hourType.getId());
      out.write("\">Delete</a></td>\n");
      out.write("        </tr>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </table>\n");
      out.write("</div>\n");
      out.write("<div class=\"login\">\n");
      out.write("    <a href=\"editHourType.jsp\">Add</a>\n");
      out.write("</div>\n");
      if (_jspx_meth_timeSheet_005ffooter_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_timeSheet_005fheadDefault_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  timeSheet:headDefault
    timeSheet.tags.CommonHeadTag _jspx_th_timeSheet_005fheadDefault_005f0 = (timeSheet.tags.CommonHeadTag) _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody.get(timeSheet.tags.CommonHeadTag.class);
    boolean _jspx_th_timeSheet_005fheadDefault_005f0_reused = false;
    try {
      _jspx_th_timeSheet_005fheadDefault_005f0.setPageContext(_jspx_page_context);
      _jspx_th_timeSheet_005fheadDefault_005f0.setParent(null);
      // /manageHourTypes.jsp(17,4) name = displayCalendar type = java.lang.Boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_timeSheet_005fheadDefault_005f0.setDisplayCalendar(false);
      int _jspx_eval_timeSheet_005fheadDefault_005f0 = _jspx_th_timeSheet_005fheadDefault_005f0.doStartTag();
      if (_jspx_th_timeSheet_005fheadDefault_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftimeSheet_005fheadDefault_0026_005fdisplayCalendar_005fnobody.reuse(_jspx_th_timeSheet_005fheadDefault_005f0);
      _jspx_th_timeSheet_005fheadDefault_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_timeSheet_005fheadDefault_005f0, _jsp_getInstanceManager(), _jspx_th_timeSheet_005fheadDefault_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_timeSheet_005fmenu_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  timeSheet:menu
    timeSheet.tags.MenuTag _jspx_th_timeSheet_005fmenu_005f0 = (timeSheet.tags.MenuTag) _005fjspx_005ftagPool_005ftimeSheet_005fmenu_005fnobody.get(timeSheet.tags.MenuTag.class);
    boolean _jspx_th_timeSheet_005fmenu_005f0_reused = false;
    try {
      _jspx_th_timeSheet_005fmenu_005f0.setPageContext(_jspx_page_context);
      _jspx_th_timeSheet_005fmenu_005f0.setParent(null);
      int _jspx_eval_timeSheet_005fmenu_005f0 = _jspx_th_timeSheet_005fmenu_005f0.doStartTag();
      if (_jspx_th_timeSheet_005fmenu_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftimeSheet_005fmenu_005fnobody.reuse(_jspx_th_timeSheet_005fmenu_005f0);
      _jspx_th_timeSheet_005fmenu_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_timeSheet_005fmenu_005f0, _jsp_getInstanceManager(), _jspx_th_timeSheet_005fmenu_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_timeSheet_005fheader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  timeSheet:header
    timeSheet.tags.HeaderTag _jspx_th_timeSheet_005fheader_005f0 = (timeSheet.tags.HeaderTag) _005fjspx_005ftagPool_005ftimeSheet_005fheader_0026_005fsub_005fnobody.get(timeSheet.tags.HeaderTag.class);
    boolean _jspx_th_timeSheet_005fheader_005f0_reused = false;
    try {
      _jspx_th_timeSheet_005fheader_005f0.setPageContext(_jspx_page_context);
      _jspx_th_timeSheet_005fheader_005f0.setParent(null);
      // /manageHourTypes.jsp(21,0) name = sub type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_timeSheet_005fheader_005f0.setSub("Hour Type Management");
      int _jspx_eval_timeSheet_005fheader_005f0 = _jspx_th_timeSheet_005fheader_005f0.doStartTag();
      if (_jspx_th_timeSheet_005fheader_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftimeSheet_005fheader_0026_005fsub_005fnobody.reuse(_jspx_th_timeSheet_005fheader_005f0);
      _jspx_th_timeSheet_005fheader_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_timeSheet_005fheader_005f0, _jsp_getInstanceManager(), _jspx_th_timeSheet_005fheader_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_timeSheet_005ffooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  timeSheet:footer
    timeSheet.tags.FooterTag _jspx_th_timeSheet_005ffooter_005f0 = (timeSheet.tags.FooterTag) _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody.get(timeSheet.tags.FooterTag.class);
    boolean _jspx_th_timeSheet_005ffooter_005f0_reused = false;
    try {
      _jspx_th_timeSheet_005ffooter_005f0.setPageContext(_jspx_page_context);
      _jspx_th_timeSheet_005ffooter_005f0.setParent(null);
      int _jspx_eval_timeSheet_005ffooter_005f0 = _jspx_th_timeSheet_005ffooter_005f0.doStartTag();
      if (_jspx_th_timeSheet_005ffooter_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftimeSheet_005ffooter_005fnobody.reuse(_jspx_th_timeSheet_005ffooter_005f0);
      _jspx_th_timeSheet_005ffooter_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_timeSheet_005ffooter_005f0, _jsp_getInstanceManager(), _jspx_th_timeSheet_005ffooter_005f0_reused);
    }
    return false;
  }
}
